### ISSUE TITLE
[Paper] Clarification on auxiliary tasks

### ISSUE THREAD

**Issue by gwendalp** [jkulhanek/robot-visual-navigation#1]
Hello, 
Thank you for making your work public. Concerning the paper (_Visual Navigation in Real-World Indoor Environments Using
End-to-End Deep Reinforcement Learning_), I don't understand well the auxiliary task consisting in reconstructing the input image and the target image, its interest? I understood it as the function materialized by the convolution network must deviate as little as possible from the input image and the target image. I may be totally wrong. Thank you for your answer.

**Comment by jkulhanek** [comment]
Dear @gwendalp,
The goal of these auxiliary tasks is to work essentially as an autoencoder, where the latent space is shared with the critic and the policy. The generated images should, therefore, be as close as possible to the input images (distance measured by MSE).
