### ISSUE TITLE
problem about transplantation

### ISSUE THREAD

**Issue by GongYanfu** [jkulhanek/robot-visual-navigation#10]
it is what happened when I run the command on Turtlebot2：python evaluate_dmhouse.py dmhouse --num-episodes 100
but in fact deepmind_lab.so exists in the corresponding path.
this problem puzzles me for about one week.
![image](https://user-images.githubusercontent.com/46698455/167242840-a89b1c4f-6cd8-485b-bb9d-6dfb9f89ff9c.png)
![image](https://user-images.githubusercontent.com/46698455/167242762-b271aa24-b370-4a2d-a6e5-494a9e78b2d5.png)

**Comment by jkulhanek** [comment]
This is a strange error. Can you compile dmhouse from source?

**Comment by rokhmatf** [comment]
looks like he's using jetson, can dmhouse and robot-visual-navigation run on jetson ?

**Comment by jkulhanek** [comment]
I think it should run there. Perhaps some dependency is missing or the version is different from what dmhouse was statically linked against? Compiling dmhouse from the source should resolve it.

**Comment by GongYanfu** [comment]
my current understanding of this paper: The virtual environment of dmhouse is not needed on a real robot? Because the virtual environment is only used for the model and training process, this process only needs to be run on the server.
question：Is dmhouse needed on turtleBot？

**Comment by GongYanfu** [comment]
understood it
