### ISSUE TITLE
error about sampling data from storage

### ISSUE THREAD

**Issue by GongYanfu** [jkulhanek/robot-visual-navigation#14]
If I use trainer "turtlebot" or "turtlebot-unreal" to train， errors occurred like below and then cause the reward of them dont normal(too low):
![image](https://user-images.githubusercontent.com/46698455/178709694-900818c2-05a9-4e29-b586-4f6c58006bdf.png)

![image](https://user-images.githubusercontent.com/46698455/178709196-07b3d33c-accd-45dd-95c7-2c301ee69fe8.png)

**Comment by jkulhanek** [comment]
I believe this is the same issue as #12. I will look into this.

**Comment by jkulhanek** [comment]
I am closing this issue for duplicity. Please continue the discussion in #14.
