### ISSUE TITLE
puzzle about training result

### ISSUE THREAD

**Issue by GongYanfu** [jkulhanek/robot-visual-navigation#16]
Is this training result normal? espacially for the result of "turtlebot" and "turtlebot-a2c"
![image](https://user-images.githubusercontent.com/46698455/180627689-9d86dd47-71fd-4fd2-9733-a63d684b5d0d.png)

**Comment by jkulhanek** [comment]
Not sure, it doesn’t look like my training results.

**Comment by GongYanfu** [comment]
Can you show the training result of this? about experiments of turtlebot, turtlebot-a2c and turtlebot-unreal

**Comment by jkulhanek** [comment]
I believe it is in the paper.
________________________________

**Comment by jkulhanek** [comment]
This should now be resolved by commit: https://github.com/jkulhanek/robot-visual-navigation/commit/2c87a2d871eb2982a1070fe4425bd1218d4958b8
