### ISSUE TITLE
[question] collect real world dataset for training

### ISSUE THREAD

**Issue by jianffu** [jkulhanek/robot-visual-navigation#21]
### 1. collect real world dataset
**there are two approach to do the task**

1). following the instruction in Collecting the original dataset for training in readme.md

>  rosrun map_collector controller.py \
>      --by 1 2
>      --by 2 2
>      --by 3 2
>      --goal 4 2

The AGV can only collect images in the setting path and only in the forward angle. 

here is the running result:
<img width="555" alt="截屏2022-09-20 16 00 58" src="https://user-images.githubusercontent.com/16053874/191206576-461b808d-d879-4514-bb0c-64855aaff4a7.png">

    
2). explore mode in map_collector ROS folder
     when we run explore function in ros/map_collector/src/main.py, the AGV move from (0,0) to (1,0), then (2,0), finally it come back (0,0) in old way. It can collect pictures in several angles in each positon.
    
here is the running result:
![未命名](https://user-images.githubusercontent.com/16053874/191206664-237003f9-be3b-4ee1-9288-66dd3d13cc31.jpg)

    

### 2. training (python train.py turtlebot)

we plan to use {name}_compiled.hdf5 from 1 to train our own model
as for agent in Reinforcement learning, each positon in hdf5 dataset must have 4 angles(0, 1, 2, 3 seperately)

In the turtle_room_compiled.hdf5 file, the dimention size 20 x 10 x 4 x 10 means each of 4 angles can store 10 photos.
<img width="1074" alt="截屏2022-09-20 14 54 14" src="https://user-images.githubusercontent.com/16053874/191206733-726d5eac-f762-4250-b143-c91d0a987d50.png">

**So, our question is which approach is correct for training? 
we think the setting path way 1) does not work in Reinforcement learning during traing. 
While, the explore method 2) when we tested can not collect the whole indoor playground.
we need collect all the images and infomations of the ground positions which AGV can visit. Is the idea true?**

**Comment by jkulhanek** [comment]
1. The first method should be preferable for collecting the images as there is a lower error in the odometry and the positions should be more precise.
2. Yes, you need to collect the entire map for the training.

**Comment by jiacheng-yao123** [comment]
> ### 1. collect real world dataset
> **there are two approach to do the task**
> 
> 1). following the instruction in Collecting the original dataset for training in readme.md
> 
> > rosrun map_collector controller.py 
> > --by 1 2
> > --by 2 2
> > --by 3 2
> > --goal 4 2
> 
> The AGV can only collect images in the setting path and only in the forward angle.
> 
> here is the running result: <img alt="截屏2022-09-20 16 00 58" width="555" src="https://user-images.githubusercontent.com/16053874/191206576-461b808d-d879-4514-bb0c-64855aaff4a7.png">
> 
> 2). explore mode in map_collector ROS folder when we run explore function in ros/map_collector/src/main.py, the AGV move from (0,0) to (1,0), then (2,0), finally it come back (0,0) in old way. It can collect pictures in several angles in each positon.
> 
> here is the running result: ![未命名](https://user-images.githubusercontent.com/16053874/191206664-237003f9-be3b-4ee1-9288-66dd3d13cc31.jpg)
> 
> ### 2. training (python train.py turtlebot)
> we plan to use {name}_compiled.hdf5 from 1 to train our own model as for agent in Reinforcement learning, each positon in hdf5 dataset must have 4 angles(0, 1, 2, 3 seperately)
> 
> In the turtle_room_compiled.hdf5 file, the dimention size 20 x 10 x 4 x 10 means each of 4 angles can store 10 photos. <img alt="截屏2022-09-20 14 54 14" width="1074" src="https://user-images.githubusercontent.com/16053874/191206733-726d5eac-f762-4250-b143-c91d0a987d50.png">
> 
> **So, our question is which approach is correct for training? we think the setting path way 1) does not work in Reinforcement learning during traing. While, the explore method 2) when we tested can not collect the whole indoor playground. we need collect all the images and infomations of the ground positions which AGV can visit. Is the idea true?**

When I run the command to collect the dataset based on the readme
`roslaunch map_collector/launch/start.launch`

`rosrun map_collector controller.py  --by 1 2 --by 2 2 --by 3 2 --goal 4 2`

I'm having some problems, the robot moves after running it, but it doesn't create a dataset folder under the /mnt/data/ folder, no images are collected. 

![code](https://github.com/jkulhanek/robot-visual-navigation/assets/156338727/820174e3-2271-4b4b-a5a1-5399cfa64531)

![1705587753847](https://github.com/jkulhanek/robot-visual-navigation/assets/156338727/5ad4d135-2169-4534-98bf-416c44c3184c)
