### ISSUE TITLE
install issues

### ISSUE THREAD

**Issue by wenzhi-zhang** [jkulhanek/robot-visual-navigation#3]
after l successfully install the DeepMind Lab,l begin to Install the deeprl package,then,l meet a error ,l don't how to deal it .

ERROR: Command errored out with exit status 1:
     command: /home/kangwen/anaconda3/envs/rvn/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/kangwen/robot-visual-navigation/deep-rl-pytorch/setup.py'"'"'; __file__='"'"'/home/kangwen/robot-visual-navigation/deep-rl-pytorch/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-p0e_oamq
         cwd: /home/kangwen/robot-visual-navigation/deep-rl-pytorch/
    Complete output (15 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/kangwen/robot-visual-navigation/deep-rl-pytorch/setup.py", line 2, in <module>
        from deep_rl import __version__
      File "/home/kangwen/robot-visual-navigation/deep-rl-pytorch/deep_rl/__init__.py", line 1, in <module>
        from .registry import make_agent, make_trainer, register_agent, register_trainer
      File "/home/kangwen/robot-visual-navigation/deep-rl-pytorch/deep_rl/registry.py", line 1, in <module>
        from .common import train_wrappers as wrappers
      File "/home/kangwen/robot-visual-navigation/deep-rl-pytorch/deep_rl/common/__init__.py", line 1, in <module>
        from .train_wrappers import MetricContext
      File "/home/kangwen/robot-visual-navigation/deep-rl-pytorch/deep_rl/common/train_wrappers.py", line 5, in <module>
        from ..core import AbstractTrainerWrapper, MetricContext
      File "/home/kangwen/robot-visual-navigation/deep-rl-pytorch/deep_rl/core.py", line 4, in <module>
        import gym
    ModuleNotFoundError: No module named 'gym'
    ----------------------------------------
WARNING: Discarding file:///home/kangwen/robot-visual-navigation/deep-rl-pytorch. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by jkulhanek** [comment]
You can resolve it by running `pip install gym`

**Comment by kangwen1011** [comment]
l have do it ,but the error become  "ModuleNotFoundError: No module named 'matplotlib".
before  Install the deeprl package,should l install all the packages
OpenAI baselines (can be installed by running pip install git+https://github.com/openai/baselines.git)
PyTorch
Visdom (pip install visdom)
Gym (pip install gym)
MatPlotLib

 ERROR: Command errored out with exit status 1:
     command: /home/kangwen/anaconda3/envs/rvn/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/kangwen/robot-visual-navigation/deep-rl-pytorch/setup.py'"'"'; __file__='"'"'/home/kangwen/robot-visual-navigation/deep-rl-pytorch/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-15n5mms4
         cwd: /home/kangwen/robot-visual-navigation/deep-rl-pytorch/
    Complete output (15 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/kangwen/robot-visual-navigation/deep-rl-pytorch/setup.py", line 2, in <module>
        from deep_rl import __version__
      File "/home/kangwen/robot-visual-navigation/deep-rl-pytorch/deep_rl/__init__.py", line 1, in <module>
        from .registry import make_agent, make_trainer, register_agent, register_trainer
      File "/home/kangwen/robot-visual-navigation/deep-rl-pytorch/deep_rl/registry.py", line 1, in <module>
        from .common import train_wrappers as wrappers
      File "/home/kangwen/robot-visual-navigation/deep-rl-pytorch/deep_rl/common/__init__.py", line 1, in <module>
        from .train_wrappers import MetricContext
      File "/home/kangwen/robot-visual-navigation/deep-rl-pytorch/deep_rl/common/train_wrappers.py", line 6, in <module>
        from .metrics import MetricWriter
      File "/home/kangwen/robot-visual-navigation/deep-rl-pytorch/deep_rl/common/metrics.py", line 6, in <module>
        import matplotlib.pyplot as plt
    **ModuleNotFoundError: No module named 'matplotlib'**

**Comment by kangwen1011** [comment]
think you very much ,after l run `pip install matplotlib`,then l successfully install the deeprl package

(rvn) kangwen@kangwen-HP-Pavilion-Gaming-Laptop-15-ec1xxx:~/robot-visual-navigation$ pip install -e deep-rl-pytorch
Obtaining file:///home/kangwen/robot-visual-navigation/deep-rl-pytorch
Requirement already satisfied: matplotlib in /home/kangwen/anaconda3/envs/rvn/lib/python3.8/site-packages (from deep-rl===develop) (3.5.1)
Requirement already satisfied: numpy in /home/kangwen/anaconda3/envs/rvn/lib/python3.8/site-packages (from deep-rl===develop) (1.22.1)
Collecting torch
  Downloading torch-1.10.1-cp38-cp38-manylinux1_x86_64.whl (881.9 MB)
     |████████████████████████████████| 881.9 MB 23 kB/s 
Requirement already satisfied: gym in /home/kangwen/anaconda3/envs/rvn/lib/python3.8/site-packages (from deep-rl===develop) (0.21.0)
Requirement already satisfied: cloudpickle>=1.2.0 in /home/kangwen/anaconda3/envs/rvn/lib/python3.8/site-packages (from gym->deep-rl===develop) (2.0.0)
Requirement already satisfied: pyparsing>=2.2.1 in /home/kangwen/anaconda3/envs/rvn/lib/python3.8/site-packages (from matplotlib->deep-rl===develop) (3.0.7)
Requirement already satisfied: python-dateutil>=2.7 in /home/kangwen/anaconda3/envs/rvn/lib/python3.8/site-packages (from matplotlib->deep-rl===develop) (2.8.2)
Requirement already satisfied: packaging>=20.0 in /home/kangwen/anaconda3/envs/rvn/lib/python3.8/site-packages (from matplotlib->deep-rl===develop) (21.3)
Requirement already satisfied: kiwisolver>=1.0.1 in /home/kangwen/anaconda3/envs/rvn/lib/python3.8/site-packages (from matplotlib->deep-rl===develop) (1.3.2)
Requirement already satisfied: pillow>=6.2.0 in /home/kangwen/anaconda3/envs/rvn/lib/python3.8/site-packages (from matplotlib->deep-rl===develop) (9.0.0)
Requirement already satisfied: cycler>=0.10 in /home/kangwen/anaconda3/envs/rvn/lib/python3.8/site-packages (from matplotlib->deep-rl===develop) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in /home/kangwen/anaconda3/envs/rvn/lib/python3.8/site-packages (from matplotlib->deep-rl===develop) (4.29.0)
Requirement already satisfied: six>=1.5 in /home/kangwen/anaconda3/envs/rvn/lib/python3.8/site-packages (from python-dateutil>=2.7->matplotlib->deep-rl===develop) (1.16.0)
Collecting typing-extensions
  Using cached typing_extensions-4.0.1-py3-none-any.whl (22 kB)
Installing collected packages: typing-extensions, torch, deep-rl
  Running setup.py develop for deep-rl
Successfully installed deep-rl-develop torch-1.10.1 typing-extensions-4.0.1

**Comment by kangwen1011** [comment]
but when l want to train scripts of the python directory,l meet the new issue,l don't know what to do next

(rvn) kangwen@kangwen-HP-Pavilion-Gaming-Laptop-15-ec1xxx:~/robot-visual-navigation$ cd python
(rvn) kangwen@kangwen-HP-Pavilion-Gaming-Laptop-15-ec1xxx:~/robot-visual-navigation/python$ python test-train.py
usage: test [-h] trainer
test: error: the following arguments are required: trainer

**Comment by jkulhanek** [comment]
You have to specify a trainer. E.g. "python test-train.py dmhouse-a2c"
