### ISSUE TITLE
Where is the image？

### ISSUE THREAD

**Issue by xiayule01** [jkulhanek/robot-visual-navigation#30]
Hello，
	I want to use that image where it was in ".../assets/images/63.pngassets/images/63.png". Can you provide it to me ?
![image](https://github.com/user-attachments/assets/24c0acc1-a201-4d14-b487-034136e62e4c)
Thank you

**Comment by jkulhanek** [comment]
This was only to test the augmentations. Feel free to replace it with any other image.
