### ISSUE TITLE
problem about dataset

### ISSUE THREAD

**Issue by GongYanfu** [jkulhanek/robot-visual-navigation#6]
are there public pre-training datasets now? if there are, how can we get it?

**Comment by jkulhanek** [comment]
Both the collected real-world dataset and dmhouse 3D simulator are publicly available. Please follow README and/or colab notebook with instructions on how to get it.

**Comment by GongYanfu** [comment]
thank you very much.

**Comment by GongYanfu** [comment]
sorry， I dont get this questions：how does the algorithm obtain the dataset for pretraining? I know that it uses dmhouse for pretrainning， but how to get dataset？
