### ISSUE TITLE
model migration

### ISSUE THREAD

**Issue by GongYanfu** [jkulhanek/robot-visual-navigation#7]
When I read the paper, I found a problem: the pre-trained simulation environment in the paper is very similar to the real environment layout used, but when we transplant the trained model to the real robot, can the real environment be inconsistent with the distribution of objects in the simulated environment? 
Waiting for your answer, thank you very much

**Comment by jkulhanek** [comment]
Of course, the distributions would be different between RW and simulated environments. In our paper, the environments indeed looked different but we showed that even in that case the model can be successfully transferred.

**Comment by GongYanfu** [comment]
ok, thanks for your answer
